-- Pragma Score Assessments Table
-- This table stores all assessment data including responses and calculated scores

CREATE TABLE IF NOT EXISTS assessments (
  -- Primary key: UUID generated by Supabase or passed from Stripe
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- User information (collected at start or from Stripe)
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  company TEXT NOT NULL,

  -- Assessment state
  status TEXT NOT NULL DEFAULT 'not_started' CHECK (status IN ('not_started', 'in_progress', 'submitted', 'report_ready')),
  current_step INTEGER NOT NULL DEFAULT 0,

  -- Assessment responses (JSONB for flexible question storage)
  -- Format: { "control-1": 4, "clarity-2": "Yes, within 5%", "clarity-5": ["CRM system", "Spreadsheets"] }
  responses JSONB DEFAULT '{}',

  -- Calculated scores (populated on submission)
  -- Format: { total, percentage, band, bandLabel, dimensions: [...], topPriorities: [...], strengths: [...] }
  scores JSONB DEFAULT NULL,

  -- AI-generated insights (populated after scoring)
  insights JSONB DEFAULT NULL,

  -- Payment tracking
  stripe_session_id TEXT,
  stripe_payment_status TEXT DEFAULT 'pending' CHECK (stripe_payment_status IN ('pending', 'paid', 'failed')),
  amount_paid INTEGER, -- in cents

  -- Demo flag (for testing without payment)
  is_demo BOOLEAN DEFAULT FALSE,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  submitted_at TIMESTAMPTZ,

  -- Indexes for common queries
  CONSTRAINT valid_email CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

-- Add columns if they don't exist (for existing tables)
-- These use DO blocks to safely add columns to existing tables
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'assessments' AND column_name = 'insights') THEN
    ALTER TABLE assessments ADD COLUMN insights JSONB DEFAULT NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'assessments' AND column_name = 'stripe_payment_status') THEN
    ALTER TABLE assessments ADD COLUMN stripe_payment_status TEXT DEFAULT 'pending';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'assessments' AND column_name = 'amount_paid') THEN
    ALTER TABLE assessments ADD COLUMN amount_paid INTEGER;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'assessments' AND column_name = 'is_demo') THEN
    ALTER TABLE assessments ADD COLUMN is_demo BOOLEAN DEFAULT FALSE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'assessments' AND column_name = 'submitted_at') THEN
    ALTER TABLE assessments ADD COLUMN submitted_at TIMESTAMPTZ;
  END IF;
END $$;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_assessments_email ON assessments(email);
CREATE INDEX IF NOT EXISTS idx_assessments_status ON assessments(status);
CREATE INDEX IF NOT EXISTS idx_assessments_created_at ON assessments(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_assessments_stripe_session ON assessments(stripe_session_id);
CREATE INDEX IF NOT EXISTS idx_assessments_is_demo ON assessments(is_demo);

-- Enable Row Level Security (RLS)
ALTER TABLE assessments ENABLE ROW LEVEL SECURITY;

-- Drop existing policy if it exists, then recreate
DROP POLICY IF EXISTS "Service role has full access" ON assessments;

-- Policy: Service role can do everything (for API routes)
CREATE POLICY "Service role has full access" ON assessments
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Drop existing trigger if exists, then recreate
DROP TRIGGER IF EXISTS update_assessments_updated_at ON assessments;

CREATE TRIGGER update_assessments_updated_at
  BEFORE UPDATE ON assessments
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Comments for documentation
COMMENT ON TABLE assessments IS 'Pragma Score assessment records with responses and calculated scores';
COMMENT ON COLUMN assessments.responses IS 'JSONB object mapping question IDs to user responses';
COMMENT ON COLUMN assessments.scores IS 'Calculated dimension scores and overall band after submission';
COMMENT ON COLUMN assessments.is_demo IS 'True for demo/test assessments that bypass payment';
